-- Base operacional de ejemplo: estos datos son sinteticos.
-- Docker ejecuta este archivo al inicializar un volumen nuevo.
CREATE SCHEMA operacion;

CREATE TABLE operacion.ciudades (
    ciudad_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE
);
CREATE TABLE operacion.clientes (
    cliente_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    ciudad_id INTEGER NOT NULL REFERENCES operacion.ciudades(ciudad_id)
);
CREATE TABLE operacion.productos (
    producto_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    precio_base NUMERIC(18,2) NOT NULL CHECK (precio_base > 0)
);
CREATE TABLE operacion.ventas (
    venta_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    cliente_id INTEGER NOT NULL REFERENCES operacion.clientes(cliente_id),
    estado TEXT NOT NULL CHECK (estado IN ('CONFIRMADA', 'ANULADA'))
);
CREATE TABLE operacion.detalles_venta (
    detalle_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id INTEGER NOT NULL REFERENCES operacion.ventas(venta_id),
    producto_id INTEGER NOT NULL REFERENCES operacion.productos(producto_id),
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(18,2) NOT NULL CHECK (precio_unitario > 0),
    UNIQUE (venta_id, producto_id)
);

INSERT INTO operacion.ciudades (nombre) VALUES
    ('La Paz'), ('Santa Cruz'), ('Cochabamba'), ('Sucre'), ('Oruro'),
    ('Potosi'), ('Tarija'), ('Trinidad'), ('Cobija'), ('El Alto');
INSERT INTO operacion.productos (nombre, precio_base) VALUES
    ('Café',25.00), ('Té',10.00), ('Galletas',8.00), ('Arroz',12.00),
    ('Azúcar',9.00), ('Leche',7.50), ('Aceite',16.00), ('Pan',0.75),
    ('Agua',3.50), ('Jugo',6.00), ('Chocolate',15.00), ('Harina',10.50);
INSERT INTO operacion.clientes (nombre, ciudad_id)
    SELECT 'Comercial Demo ' || lpad(n::text, 2, '0'), ((n - 1) % 10) + 1
    FROM generate_series(1,40) AS n;
INSERT INTO operacion.ventas (fecha, cliente_id, estado)
    SELECT DATE '2026-09-01' + ((n - 1) % 36), ((n - 1) % 40) + 1,
           CASE WHEN n % 20 = 0 THEN 'ANULADA' ELSE 'CONFIRMADA' END
    FROM generate_series(1,300) AS n;
INSERT INTO operacion.detalles_venta (venta_id, producto_id, cantidad, precio_unitario)
    SELECT v.venta_id, p.producto_id, ((v.venta_id * 2 + linea) % 8) + 1,
           round(p.precio_base * CASE WHEN v.venta_id % 5 = 0 THEN 0.95 ELSE 1 END, 2)
    FROM operacion.ventas AS v
    CROSS JOIN generate_series(1,2) AS linea
    JOIN operacion.productos AS p ON p.producto_id = ((v.venta_id + linea - 2) % 12) + 1
    ORDER BY v.venta_id, linea;
CREATE INDEX detalles_venta_venta_idx ON operacion.detalles_venta(venta_id);
CREATE INDEX ventas_fecha_idx ON operacion.ventas(fecha);
