"""Interfaces implementadas por los adaptadores de infraestructura."""

from typing import Protocol

from datalake_demo.domain.models import GoldRow, RawSale, RejectedSale, Sale
from datalake_demo.etl.models import (
    BronzeResult, CurrentPublication, Execution, GoldResult, PreparedPublication,
    PublicationResult, Quality, SilverResult, SourceSnapshot,
)


class SalesSource(Protocol):
    def read_snapshot(self) -> SourceSnapshot: ...


class Clock(Protocol):
    def __call__(self) -> str: ...


class LakeRepository(Protocol):
    def write_bronze(self, execution: Execution, snapshot: SourceSnapshot) -> BronzeResult: ...
    def read_bronze(self, bronze: BronzeResult) -> list[RawSale]: ...
    def write_silver(self, bronze: BronzeResult, sales: list[Sale], rejected: list[RejectedSale],
                     quality: Quality) -> SilverResult: ...
    def read_silver(self, silver: SilverResult) -> list[Sale]: ...
    def write_gold(self, silver: SilverResult, rows: list[GoldRow]) -> GoldResult: ...
    def prepare(self, gold: GoldResult) -> PreparedPublication: ...
    def read_publication(self, prepared: PreparedPublication) -> tuple[list[GoldRow], Quality]: ...


class PublicationRepository(Protocol):
    def begin(self, dataset: str, execution_id: str, source_type: str, created_utc: str) -> Execution: ...
    def captured(self, execution: Execution) -> BronzeResult | None: ...
    def bind_bronze(self, bronze: BronzeResult) -> BronzeResult: ...
    def current(self, dataset: str) -> CurrentPublication | None: ...
    def publish(self, prepared: PreparedPublication, rows: list[GoldRow], quality: Quality) -> PublicationResult: ...
